version: '3'
services:

  ### Nginx container #########################################

  nginx:
    image: nginx:1.14.2-alpine
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./www:/app:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./log/nginx:/var/log/nginx:rw
    restart: always
    networks:
      net-default:
        ipv4_address: 172.22.0.2

  ### Java container #########################################

  java:
    build:
      context: ./build/java
    expose:
      - "21230"
    restart: always
    networks:
      net-default:
        ipv4_address: 172.22.0.3

  ### PHP container #########################################

  php:
    build:
      context: ./build/php
    expose:
      - "9000"
    volumes:
      - ./www:/app:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php:/var/log:rw
      - ./crond/root:/var/spool/cron/crontabs/root:rw
    restart: always
    extra_hosts:
      - "admin.local.com:172.22.0.2"
      - "api.local.com:172.22.0.2"
      - "pay.local.com:172.22.0.2"
      - "salesapi.local.com:172.22.0.2"
    networks:
      net-default:
        ipv4_address: 172.22.0.4

  ### Mysql container #########################################

  mysql:
    image: mysql:5.6.42
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db:/var/lib/mysql:rw
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./log/mysql:/var/log/mysql:rw
    restart: always
    networks:
      net-default:
        ipv4_address: 172.22.0.5

  ### Redis container #########################################

  redis:
    image: redis:5.0.4-alpine
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ./conf/redis/redis.conf:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      net-default:
          ipv4_address: 172.22.0.6

  ### mongodb container #########################################

  mongodb:
    image: mongo:4.0.9-xenial
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
    volumes:
      - ./mongodb:/data/db:rw
    restart: always
    networks:
      net-default:
          ipv4_address: 172.22.0.7

  ### yapi container #########################################

  yapi:
    build:
      context: ./build/yapi
    ports:
      - "3000:3000"
    volumes:
      - ./log/yapi:/api/log:rw
    depends_on:
      - mongodb
    restart: always
    networks:
      net-default:
          ipv4_address: 172.22.0.8

networks:
  net-default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
